# three node (two workers) cluster config
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
- role: worker
  extraPortMappings:
    - containerPort: 30082
      hostPort: 8443
      protocol: TCP
    - containerPort: 30083
      hostPort: 27017
      protocol: TCP
    - containerPort: 30084
      hostPort: 27018
      protocol: TCP
    - containerPort: 30085
      hostPort: 27019
      protocol: TCP
    - containerPort: 30080
      hostPort: 8080
      protocol: TCP
    - containerPort: 30081
      hostPort: 8081
      protocol: TCP
    - containerPort: 389    # Port inside the container (LDAP port)
      hostPort: 389         # Port on the host machine (exposed)
      protocol: TCP
    - containerPort: 30002  # Optionally expose a different external port (NodePort)
      hostPort: 30002       # Port on the host machine for NodePort access
      protocol: TCP
- role: worker
