apiVersion: v1
kind: Service
metadata:
  name: openldap-service
  namespace: mongodb  # Replace with your namespace
spec:
  selector:
    app: openldap
  ports:
    - protocol: TCP
      port: 389
      targetPort: 389
      nodePort: 30002  # Choose an available port for external access
  type: NodePort
